name: paginated_builder
description: A set of Widgets to paginate through data from any data source
repository: https://github.com/SupposedlySam/paginated_builder/blob/jonahwalker/test/package/README.md
version: 0.2.1

# See https://docs.flutter.dev/development/tools/sdk/releases?tab=macos for versions
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  chunk: ^1.0.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

scripts: derry.yaml
