name: paginated_builder
description: A new Flutter package project.
version: 0.0.1

publish_to: none

# See https://docs.flutter.dev/development/tools/sdk/releases?tab=macos for versions
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  chunk: ^1.0.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

scripts: derry.yaml
